const chalk = require('chalk')
const pack = require('../package.json')

require('./lib/generators')(hexo)
require('./lib/injector')(hexo)

hexo.on('generateAfter', function () {
  console.log(
    chalk.green('INFO ') +
      chalk.yellow('API data generated by') +
      chalk.cyan.bold(' Lyra v' + pack.version)
  )
})

hexo.on('exit', function () {
  console.log(
    chalk.green('INFO ') +
      chalk.magenta('Thanks for using') +
      chalk.cyan.bold(' Mariges v' + pack.version)
  )
  console.log(
    chalk.green('INFO ') +
      chalk.magenta('Check out the repo at: ') +
      chalk.cyan.underline(pack.repository)
  )
})
